name: starwinds-magnetogram
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - matplotlib
  - pip
  - psutil
  - quaternion
  - spherical_functions
  # Nbstripout is used with git
  - nbstripout
  #
  # These are for testing
  #
  - pytest
  - nbval
  - pytest-cov
  - pip:
    - pytest-console-scripts
  #
  # For Codacy integration
  #
  - codacy-coverage
  