name: starwinds-magnetogram
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy<1.17  # Due to announced deprecation of lpmn and other functions. 
  - matplotlib
  - pip
  - psutil
  - quaternion  # Note: this refers to https://github.com/moble/quaternion
  - spherical_functions
  - numba
  # Nbstripout is used with git
  - nbstripout
  #
  # These are for testing
  #
  - pytest
  - nbval
  - pytest-cov
  - pip:
    - pytest-console-scripts
  #
  # For Codacy integration
  #
  - codacy-coverage
  