name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: |
            pyproject.toml
            requirements.txt

      - name: Install package (and test extras)
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]

      # Optional lint (uncomment if you add flake8/ruff to extras OR install here)
      # - name: Lint
      #   run: |
      #     pip install ruff
      #     ruff check .

      - name: Run tests
        run: |
          pytest --cov=starwinds_magnetogram --cov-report=xml:pytest-cobertura.xml -q

      - name: Upload coverage to Codacy
        if: always()
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: pytest-cobertura.xml

      - name: Build sdist/wheel and validate metadata
        run: |
          pip install build twine
          python -m build
          twine check dist/*
