# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: Build
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Test environment variables
      env:
        MY_TEST_SECRET: ${{ secrets.MY_TEST_SECRET }}
      run: |
        echo ${MY_TEST_SECRET}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        python -m pip install versioneer
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Install package in order to test entry points
      run: |
        echo "Test secret: $MY_TEST_SECRET"
        # Install the package itself
        python -m pip install --user --editable .
    - name: Test with pytest
      run: |
        pytest --cov=starwinds_magnetogram --cov bin --cov-report=xml:pytest-cobertura.xml
    - name: Codacy Coverage Reporter
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        # api-token: ${{ secrets.CODACY_API_TOKEN }}
        coverage-reports: pytest-cobertura.xml
      uses: codacy/codacy-coverage-reporter-action@v1.3.0

